- src/components/modal.js
`updateConfig` destroys the DOM node which was a problem if a custom DOM node was being passed in because then it wouldn't exist the next time around. 
@harisaurus @michelleyschen @tanema
> prevent modals from disappearing for good after updateconfig

- src/buybutton.js
so. 
If require.js is included on the page, then then `import ShopifyBuy` will fail if I'm pointing to the UMD build, because the umd script will be like "hey is `window.define` a thing?" and window will be like "you bet" and then it's like ok I guess i'm _not_ going to `module.exports` so then I get NOTHING. 
the es6 build is about 10kb bigger.
@tanema @michelleyschen
cc @mikkoh @minasmart
> consume es6 instead of umd

- src/styles/embeds/sass/components/_collection.scss
ensure collection products are centered and vertically aligned with correct fallbacks for flexbox
- collection wrapper currently removed reverted `display: flex` to `block` at smaller breakpoints. this was unnecessary and therefore removed
- when flexbox is unavailable, the inline-blocked elements require `vertical-align:top` to be top aligned, along with `text-align:center` on the wrapper element for them to be horizontally centered
@tanema @tessalt @michelleyschen 
**Before**
**After** (Both with flexbox, and with flexbox fallbacks)
> collection product style fixes

- src/components/product-set.js
- test/unit/product-set.js
fixes the broken embed on the blog post. `collection_sort` param was being sent for both collections and arrays of product IDs. API does not like it when it gets `collection_sort` but no `collection_id`
@michelleyschen @harisaurus @tanema
> Fix product sets

- src/defaults/components.js
Fix https://github.com/Shopify/buy-button/issues/2015
@tessalt @harisaurus
> make sure the checkout popup would have scroll bar in all browser

- package.json
- script/build.js
turns out UMD is no good for third-party js because it looks for `define` and makes decisions based on that which is bad because sometimes people do crazy things like use requirejs. 
I also got rid of the es6 build because it's untested. 
I also made sure we're rm -rf ing lib because I forgot to before because I'm bad. 
once https://github.com/Shopify/js-buy-sdk/pull/266 merges I can fix the requirejs bug. 
@michelleyschen @tanema cc @mikkoh
> export commonjs

- src/ui.js
directly calling `_resizeY` was obviously a bad idea, since `resize` should always called directly as it contains the logic for whether or not `_resizeX` and `_resizeY` should be called. 
@harisaurus @tanema @michelleyschen
> prevent calling resize on iframe-less components

- src/components/cart.js
- src/styles/embeds/sass/components/_cart.scss
- test/unit/cart.js
Fix https://github.com/Shopify/buy-button/issues/2020
1. Fix the typo that broke the add item animation (`flipin` to `flipIn`)
2. Refactor out animation for remove item as `flipOut` (and totally on purpose cuz I was flip out over css animation)
3. remove `transform-style: preserve-3d;` as it break cart look & feel for firefox 49.0.2
@harisaurus @tessalt @richgilbank
> Cart animation fix

- src/styles/embeds/sass/components/_collection.scss
Because autoprefix is on hold,
this will fix Safari layout for now.
Before:
After:
@harisaurus @tessalt
> add in safari prefix to fix safari flex box issue

- src/defaults/components.js
- src/styles/embeds/sass/components/_product.scss
- src/templates/product.js
- Add a wrapper to the button template
- Update styles to accomodate the above mentioned changes
These changes allow us to set the `text-alignment` on the product wrapper and align all the elements inside to the left/center/right.
@tessalt @tanema @michelleyschen 
a 🎩  would be appreciated
Examples:
> add a wrapper element to buttons to properly control alignment

- src/component.js
- src/ui.js
currently, tracker throws if a product does not exist because it tries to access properties on nonexistent model. Should catch those and report. 
@michelleyschen @tanema @harisaurus
> Don't try to track failed embeds

- src/component.js
First part fix for https://github.com/Shopify/buy-button/issues/2027
Tested with the currency moneyFormat string (ie. £{{amount}})
and URI encoded format string (ie. %C2%A3%7B%7Bamount%7D%7D)
Both works!
@harisaurus @tessalt 
This depend on https://github.com/Shopify/buy-button-js/pull/299 for some edge case detecting.
> [DO NOT MERGE] Money format decode

- src/ui.js
- src/utils/track.js
adds `referrer` and `subdomain` fields to properties sent to trekkie.
@zqureshi @richgilbank @tanema @michelleyschen
> add additional tracking props

- src/components/toggle.js
Fix https://github.com/Shopify/buy-button/issues/2050
@harisaurus @tessalt @tanema
> force cart toggle to not re-calculate height.

- package.json
transpile src on prepublish so that consumers can pull in commonjs modules (buy button app needs the defaults file)
@tanema @michelleyschen @harisaurus
> transpile src to lib

- src/buybutton.js
- src/components/cart.js
- src/ui.js
supports multiple domains on the same page. While you'll end up with 2 carts, if you're sending people straight to checkout it works fine.
changing the reference to UI instance(s) from `ui` to `domains` and it is now a hash not an object. Doesn't break the API because `init` still returns the most recently created instance.  
@tanema @harisaurus @michelleyschen
> Support multi domain

- src/defaults/components.js
To address @richgilbank comment https://github.com/Shopify/buy-button-js/pull/315
@andreygargul requested that all button text to stay all cap,
and the total text to be update to `SUBTOTAL` and in all cap.
@harisaurus @tessalt @tanema
> update the cart total text to be subtotal and in call cap

- src/components/checkout.js
- src/defaults/components.js
allow users to pass `options.cart.popup = false` to redirect current page to checkout instead of opening a new page. 
Are there consequences to do this or reasons we didn't do this before? I don't remember. 
@tanema @michelleyschen @harisaurus @richgilbank
> add option to open checkout in same pane

- src/component.js
Apparently `.contains` does not work on `document` in IE (https://connect.microsoft.com/IE/feedback/details/780874/node-contains-is-incorrect)
This PR calls it on document.body instead.
> don't call .contains on document

- src/components/product.js
fixes https://github.com/Shopify/buy-button/issues/2080
button should never be disabled if it is linking to modal. 
@tanema @harisaurus @michelleyschen
> enable button on out of stock if modal

- src/components/toggle.js
Fix https://github.com/Shopify/buy-button/issues/2082
This bug is cause by the fact that `resize` is usually call in the render step, and in terms of `toggle`, its get resize before the `is-active` class is apply. 
This mean the button has `display:none` on its iframe wrapper, and the dom element inside the iframe will calculate to 0px in Firefox, but in Chrome calculate it correctly.
To resolve it, I am forcing a `resize` after the class has been applied. 
@harisaurus @tanema @richgilbank @tessalt
> resize after is-active class get added

- src/components/cart.js
if you  had a cart in localStorage, the new `lineItem.imageVariants` field wouldn't be populated. This checks to see if it exists before using it. 
@michelleyschen @harisaurus
> fix line item images for old carts

- src/view.js
add in code that was accidentally remove from https://github.com/Shopify/buy-button-js/pull/307
> add back missing life cycle event

- docs/advanced/index.md
- script/embed-styles.js
- src/components/toggle.js
- src/styles/embeds/buybutton.css
- src/styles/manifest.scss
- src/ui.js
- src/updaters/product.js
- src/view.js
- src/views/cart.js
- src/views/modal.js
- src/views/toggle.js
- test/unit/modal.js
generates a buybutton.css file that can be pushed up to cdn and used by people not using iframes. Had to make a few changes to the code where I'd been assuming the presence of iframes. 
@michelleyschen @richgilbank
> export css for no-iframe option

- src/components/product-set.js
- src/components/product.js
so i think https://github.com/Shopify/buy-button/issues/2121 is happening because sometimes the product set creates the cart first instead of the product, because the cart is created after the ajax request. This was to try to get data back as soon as possible, but we should keep the synchronous tasks running first so they run in order. Hard to test this.... but i couldn't reproduce the error locally and i had been able to occasionally before.
@michelleyschen @harisaurus
> switch creation order of components

- docs/customization/index.md
I was looking for the possibility to proceed to the checkout within the same window. After studying the code I found this undocumented option which is [checked](https://github.com/Shopify/buy-button-js/blob/2b1791de3d5f49eed55f5c1074cd980a77e5f603/src/components/checkout.js#L16) in the Checkout.js.
> update docs with popup cart option

- src/components/product.js
so i'm getting a lot of errors in bugsnag for `Cannot read property 'productTitle' of undefined` coming from line 373. All instances are for attempts to retrieve products that don't exist... but `trackingInfo` should never be called in those cases and I haven't been able to trigger the bug even under the conditions bugsnag reports. 
Anyways, this should shut that up, at least.
> dont try to track empty models

- src/component.js
through a long chain of unfortunate complex things, this swallowed error was causing the "Not found" error to be incorrectly reported to bugsnag as `Cannot read property 'productTitle' of undefined`
@tanema @michelleyschen @harisaurus
> don't swallow errors

- src/iframe.js
this was a bit of a weird one. Basically there are multiple states of a font being loaded in the webfont loader, and until the final state ("active"), safari can't accurately calculate an element's width, leading to bugs like https://github.com/Shopify/buy-button/issues/2134 
http://stackoverflow.com/questions/4701892/accurate-width-of-element-when-using-font-face-in-chromium
So ive changed it so that the promise for loading fonts is resolved only when the `fontactive` event fires (or after 1 second if it never fires).
@michelleyschen @harisaurus @tanema
> wait for fontactive to render

- src/styles/embeds/sass/components/product.css
A broken image icon currently appears on older versions of Firefox when no-image is present (https://github.com/Shopify/buy-button/issues/2138). It also causes the iframe to size incorrectly. This PR addresses the issue by hiding the image wrapper when `no-image` is present.
**Before**
**After**
> hide the image wrapper if no image is present

- .gitignore
- docs/_includes/header.html
- docs/_layouts/wide.html
- docs/_sass/custom/custom.scss
- docs/_sass/custom/layout.scss
- docs/configuration/index.html
adds a new /configuration page to the docs with a crazy huge table of ALL the possible config options. No matter what we do with the docs, we can link to this table whenever we're like "and you can find all the options here" 
added some bad css, sorry. 
@harisaurus @michelleyschen
> udpate docs with config page

- src/defaults/components.js
Provide `imgWithCarousel` a position in the template order otherwise the featured layout doesn't know where to render the carousel version (therefore not rendering it at all).
> add default positioning for image with carousel for product

- src/images/arrow.svg
- src/styles/embeds/sass/components/product.css
- update arrow svg
- ensure no margins are applied to horizontal layouts
- selected carousel item opacity now lower to better distinguish selected vs not selected
**Before**
**After**
> fix opacity, update chevron svg, update margin for modalProduct

- src/styles/embeds/sass/utilities.css
- src/views/toggle.js
fixes #371 
I did a few things to hopefully make it accessible however I am not an expert at these things so please let me know if something could have been done in a different way.
what I did.
- added `aria-label` to the toggle
- added `role='button'` to the toggle
- added a visibility-hidden text block that is present only when the title is not shown and using the title text.
> Adding screenreader functionality to the cart toggle

- src/views/product.js
the iframe should be resizing to the height of the wrapper when its contents are loaded. this broke due to `component.model.selectedVariantImage` no longer existing on the model.
> fix iframe resize based on initial image load

- src/components/product-set.js
- src/components/product.js
- test/unit/product-set.js
- test/unit/product.js
depends on: https://github.com/Shopify/js-buy-sdk/pull/387
this change allows existing buy buttons, which historically used numerical shopify product IDs, to be transformed into our GraphQL API's product IDs so that they don't fall over once we roll out the updated `buy-button-js` library to existing buy button embeds.
> adapt old config to new standards

- src/component.js
- src/components/product.js
- test/unit/product.js
change the property names to be more clear about when we are using a storefrontId rather than a shopify product id
addresses #405
> use storefrontId rather than id in Product class

- dev.yml
- package.json
- src/components/cart.js
- src/components/product.js
- src/updaters/product.js
- test/unit/cart.js
- test/unit/product.js
- yarn.lock
- Update node version in `dev.yml`
- Bump jsbuysdk version for bugfixes
- `clearLineItems` no longer exists. Update to use `removeLineItems` for emptying cart
- Update image getter
- Use 480 as default if no embed width is provided
- If % width is provided, use 1000px instead. The % situation is most common for when creating full width embeds using 100%, so 1000px addresses all breakpoints
- Re-add `isSelected` to carousel images to show selected image
> Various fixes

- src/components/product.js
- src/updaters/product.js
- src/utils/normalize-config.js
- test/fixtures/product-fixture.js
- test/unit/product.js
- normalize variant ids when present, and use normalized variant id instead of database key.
- a bunch of normalizers
- tiny fixes
> set storefront variant id when variant id is set + fixes

- readme.md
Fix typo in readme by replacing `intsall` with
`install`.
> Fix typo in readme about installing jekyll

- src/view.js
- test/unit/view.js
Anytime the config is changed for an embed, `init` is called. This calls `delegateEvents` which would create event listeners for the required elements. This was an issue as multiple listeners were attached to the same elements over and over anytime the config was updated, which would cause crazy behaviour in the Buy Button app.
There should ideally be an `init` and a similar `update` method, the latter not rebinding events, but that would require a bunch of rework. Adding in the simpler, but not really elegant, solution as a flag that is checked before the events are bound.
Ping me for 🎩 -ing instructions to test buybuttonjs with buybutton.
> prevent events from binding again on re-inits

- index.example.html
- src/components/product.js
- src/templates/product.js
- src/ui.js
- test/unit/product.js
- Updated the `index.example.html` starter file
- Added a new key to the `image` object for `srcLarge`. We need to use this for horizontal layouts and primary images in the modal. The current `src` url image has a max height/width of 480 which is not sufficient.
`srcLarge` isn't the best name. if you've got a better suggestion that'd be sweet. also, ideally the `src` key should just have various sizes listed under it, but this will require significant change. we can perhaps focus on that at a later time.
> add srcLarge for default horizontal layouts and update example

- src/components/cart.js
- src/components/product.js
This also properly opens the checkout window synchronously when the button destination is `checkout`, and is compatible with non-straight-to-checkout buttons on the page
> always use a checkout for the checkout button destination.

- package.json
- yarn.lock
This contains `compareAtPrice` on variants which is needed upstream
> Update to v1.0.2 of js buy

- package.json
- src/components/cart.js
- test/unit/cart.js
- yarn.lock
Bump the `shopify-buy` version and `fetchData()` to use the newly added behaviour. 
The code assumed that if `checkoutId` is defined in local storage, it's also valid. This isn't always the case and the behaviour is accounted for in this PR.
> Fix behaviour for invalid localStorage key

- src/components/product.js
- test/unit/product.js
In certain scenarios we were seeing issues with the `ID` field because we were trying to fetch with `["someId"]` instead of `"someId"`.
> Extract storefrontId if it's in an array

- src/components/cart.js
- src/components/product.js
- test/unit/product.js
Latest storefront failure was due to `selectedVariant.image` being undefined. This PR should address the issue by using the `NO_IMG_URL` form cdn, or the first product image, if it exists
> Fallback strategy when no variant or product image is defined

- src/components/product.js
- test/unit/product.js
`describeOptions` would sometimes select multiple options if we have duplicated values in different dropdown lists. This PR should fix it
> Fix describe options to only ever select 1 option

- package.json
- yarn.lock
[This update](https://github.com/Shopify/js-buy-sdk/pull/485) is needed so we can fix [#2336](https://github.com/Shopify/buy-button/issues/2336)
> Update js-buy-sdk version

- src/components/cart.js
JS errors are preventing a lot of shops from adding products to carts.
Reverts Shopify/buy-button-js#450
> Revert "Use default product image in thumbnail if defined"

- src/components/product.js
- test/unit/product.js
When we're pulling an invalid variant, buy buttons would stop working and show `unavailable` text instead. This PR will add a fallback method for handling those cases and default to the first variant if the selected `variantId` was invalid.
> Handle invalid variantId

- src/components/cart.js
- test/unit/cart.js
When a variant has no image with it, instead of using `NO_IMG_URL` try getting the first product image first.
> Fix line item image in cart

- package.json
- src/buybutton.js
- src/components/cart.js
- test/unit/cart.js
- yarn.lock
This stops pages with multiple embeds from different shops and different
channels from clobbering each others cart IDs
> Make the checkout local storage key unique per shopify buy client

- src/ui.js
- test/unit/ui.js
We seem to be sending a promise instead of a subdomain to trekkie. This should fix it.
> Use domain from client.config

- src/components/product.js
- test/unit/product.js
This relates to #489 but offers a different approach to resolving the multi-item checkout problem. After discussing the behaviour with UX, it was decided that clicking the direct checkout button should not result in the cart toggle appearing. From a buyer's perspective, direct checkout buttons should not be associated to building a cart. Additionally, if multiple buy buttons are embedded on a page, the direct checkout buttons should not interfere with any cart which may exist for the other buttons. 
Note: This change would make it impossible for a product available via a direct checkout button to be purchased in a multi-item cart. 
- A new checkout is created when the direct checkout button is clicked, and the variant is added to that cart. 
- The webUrl for that cart is used for the …
> Create a new checkout to manage direct checkouts

- src/components/product.js
- src/ui.js
- test/unit/product.js
Looking to add a bit more attributes to the current tracking to be able to calculate click-rate
For this we need to have amounts of click + amounts of views per destination
- Add visibility around the `buttonDestination` attribute
- Track the event of direct checkout being clicked
With a custom tracker that logs the events, I was able to test locally
> Add more tracking for the product component

- src/components/product.js
- test/unit/product.js
In #490, the direct checkout behaviour was updated to create a new cart for checkout, and add the selected variant to it. However, a quantity of 1 was always being added, regardless of the quantity input. 
This PR adds the expected quantity to the cart. 
Before:
After:
> Fix direct checkout quantity

- src/components/cart.js
- test/unit/cart.js
The `moneyFormat` passed in via `createComponent` is available on the `globalConfig` not on `config`, which is causing the cart's money format to always be fetched from the js-buy-sdk. 
To determine whether we need to be fetching it from the sdk, we should be checking `this.moneyFormat`, which is being set in the constructor based off of the `globalConfig` value.
> Use the globalConfig's moneyFormat for the cart

- src/templates/cart.js
- src/templates/line-item.js
In this PR, HTML escaping will be re-added to the `pricing` values within `cart` and `line-item` templates. This fixes [#2455](https://github.com/Shopify/buy-button/issues/2455).
> Re-add html escaping to cart total and line-item prices

- src/views/product.js
- test/unit/product.js
- test/unit/view.js
This PR updates the `product` component to always return the `clientHeight` as the outer height of the product container.  This outer height is used to set the height of the `iFrame` container.
Fixes: [#2497](https://github.com/Shopify/buy-button/issues/2497), [#2452](https://github.com/Shopify/buy-button/issues/2452), [#2366](https://github.com/Shopify/buy-button/issues/2366)
> Add custom outerHeight() to Product component to always return clientHeight

- src/components/product.js
- test/unit/product.js
Fixes #501 using the solution proposed in that issue. This is also the method of opening a blank popup window proposed in the MDN docs (https://developer.mozilla.org/en-US/docs/Web/API/Window/open).  The existing implementation of passing in `null` failed because some browsers stringify a null DOMString, causing `'null'` to be appended onto the parent window's url (https://developer.mozilla.org/en-US/docs/Web/API/DOMString). 
Tested on the following browsers, to verify that an `about:blank` page appears before redirecting to the checkout: 
- MacOS: Chrome, Safari, Firefox, Opera
- iOS: Safari, Chrome, Firefox
- Windows VM: Edge, IE11, Firefox, Chrome
> Open popup window with an empty url to prevent flashing a 404 page

- test/unit/cart.js
- test/unit/product.js
Removed deprecated use of sinon.spy() with three parameters
Stubbed init to avoid fetch calls on the client
> Fixed console errors that appear while running tests

- test/unit/ui.js
- Removed appendChildStub from prototype methods beforeEach
- Added appendChildStub to describe blocks that need to stub it
- Cleared products after each createProduct test finishes
> moved appendChildStub deeper into tests

- src/components/product.js
- test/unit/product.js
Closes https://github.com/Shopify/buy-button-js/issues/370.
This exposes the original, un-transformed image source URL on the product resource that clients can use to display high-resolution images on their Buy Buttons.
> Expose originalSrc on product.image

- test/unit/iframe.js
- Reformatted test to match format of other tests (constructor and prototype methods separated)
- Created tests for constructor
- Refactored and created tests for load()
- Refactored and created tests for loadFonts()
- assert.isUndefined is used to check for return resolve() calls
- commented out loadFontScript() tests (will be refactored in future PR)
> Update iframe.js tests part 1

- test/unit/product.js
The following was doing in product.js:
- Organized tests into which file/class it is from (component/updater/view)
- Separated constructor and prototype methods
- Fixed eslint errors
- Grouped getters
- Followed stubbing conventions (store in a variable outside of objects and always restoring)
- Changed .then() to async await
What still needs to be done:
- Consider whether future tests should still depend on init()
- Fix issue where many div wrappers are being created without cleanup
- Fix console errors involving missing images
- More test-specific cleanups that involve heavier logic
- Re-evaluating how props is created
- There are many instances where product is being re-instantiated in the same test 
The test, 'converts shopify product id to storefrontId', was separated as it did not …
> Cleanup product unit tests

- test/unit/product/product-component.js
- Updated/created tests for constructor, init, sdkFetch, and updateVariant
- moved sdkFetch out of other prototype methods because it uses its own Product instantiation
- removed a constructor test that depended on normalizeConfig
> Refactor existing product component tests part 1

- test/unit/product/product-component.js
- Moved sdkFetch into other prototype methods
- Refactored sdkFetch to not re-instantiate a new product component
- Updated tests for setupModel
- Created tests for:
- onBlockButtonKeyup
- onOptionSelect
- onQuantityBlur
- onQuantityIncrement
- closeCartOnBgClick
> Update product component prototype methods pt3

- test/unit/checkout.js
This was not put into a folder like the other children classes because checkout only has component and does not have a view or updater class.
Also, open does not check the location of window because it is currently not possible
> Updated tests for checkout component tests

- package.json
- yarn.lock
Bump JS Buy SDK to version 1.11.0, which was released November 27, 2018.
🎩ed locally on a test shop.
> Bump js-buy-sdk to version 1.11.0

- package.json
- yarn.lock
We want to pull in the latest changes from js-buy-sdk to fix the automatic discounts error. To achieve this error, you need to set up an automatic discount in admin (such as Buy X Get Y), and try to add X and Y to your cart. 
If you want to 🎩 : 
* Run locally on master and verify that the error is reproducible when adding X and Y to cart
* Run on this branch and verify that both X and Y can be added to cart without error
> Bump js buy sdk to v2.0.1

- src/components/product.js
- src/templates/product.js
- test/unit/product/product-component.js
**Description**
As a developer
I want the alt text variable exposed on my Product Detail Page (PDP) images
So that I can properly set the alt text data, which exists in shopify, on the `alt` attribute of the main image and `aria-label` attribute on the carousel images.
**Acceptance Criteria**
* the `alt` and `aria-label` attribute data comes from the image alt text field in the shopify store
* the `aria-label` attribute is set the selected carousel image
* the `aria-label` attribute is set on the carousel image
* the `alt` attribute is set on the main image
> add alt text to images

- test/unit/product/product-component.js
**What are you trying to accomplish with this PR?**
* Stub out imageAltText
* Update some `image > return object` test names to include `altText`
* Update the assertion in the `imageAltText` test to use the model's product title, instead of a hardcoded value pulled from the fixture
cc: @robskrob
> Update tests related to image alt text

- src/components/cart.js
- src/defaults/components.js
- src/styles/embeds/sass/components/cart.css
- src/templates/cart.js
- test/unit/cart.js
**What are you trying to accomplish with this PR?**
Expose a note field at the cart level, which will populate the checkout object's [note field](https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/object/checkout#note). 
I've added a new contents option called `note`, a new text field called `noteDescription`, as well as several classes which can be used to override the default styling. 
The styling of the cart note follows the existing convention of using padding around the scrollable area where the line items appear. However, this method does not allow for a long cart notice or note description text without cutting off some of the scrollable area.  This was the case before as well, for long cart notice strings. 
To 🎩 : 
* Check that the new config options work …
> Add notes field to cart

- src/styles/embeds/sass/components/cart.css
- src/styles/embeds/sass/components/quantity.css
***Problem***
Currently in Firefox, the cart quantity input field is showing the browser increment/decrement arrows. Also, when a user scrolls up a longer cart item list, the list is showing underneath the cart header.
***Solution***
Update the CSS by adding a background color to the cart header and rearranging the browser specific input appearance style property.
🎩 on:
> Fix Firefox cart styling

- docs/customization/index.md
Add the new cart note related configuration defaults to the docs, to give developers an indication of how to enable the feature. 
Should match the [cart > contents > note default](https://github.com/Shopify/buy-button-js/blob/master/src/defaults/components.js#L198) and [cart > text > noteDescription default](https://github.com/Shopify/buy-button-js/blob/master/src/defaults/components.js#L228)
> Update docs with new cart config options

- CHANGELOG.md
- package.json
- src/components/cart.js
- test/unit/cart.js
- yarn.lock
- Bump `shopify-buy` dependency to `v2.2.0`.
- Asserts `lineItemsSubtotalPrice` is exposed.
- Expose `formattedLineItemsSubtotal` field to cart view model. The new field consists in a sum of all line items prices without any discount, taxes or shipping rates applications.
> Add support to lineItemsSubtotalPrice field

- src/components/product.js
- src/utils/detect-features.js
- test/test.js
- test/unit/cart.js
- test/unit/detect-features.js
- test/unit/product/product-component.js
To prevent `window.open` from being called when it is not properly supported by the browser, a new function was added to check for unsupported user agents. 
To 🎩 : 
* Verify that popup functionality in other browsers is supported
* Verify that direct checkout will open the web checkout on the following iOS in-app browsers:
> Add check for user agent before window.open

- package.json
- yarn.lock
Bump js-buy-sdk version to pull in an updated version of graphql-js-client that fixes an IE browser support issue via https://github.com/Shopify/graphql-js-client/pull/128
> Bump js-buy-sdk to v2.2.1 for IE support

- src/components/product-set.js
Currently, the product set component ignores the `cartNode` set at the global level. Therefore, it is always appending new dom nodes to the document for the cart when initializing a collection buy button.
This PR updates the product set component to pass through the `cartNode` option when creating a cart, like the [product component](https://github.com/Shopify/buy-button-js/blob/master/src/components/product.js#L536). 
To test:
* pass in a reference to a dom node in the config's top level `cartNode` option
* verify that the cart renders inside the node, instead of appending new divs to the document
> Use the global config cart node for product sets

- src/updaters/product-set.js
- test/unit/product-set.js
* Use the same logic as the product component's `updateConfig` to update the modal of the first product in a product set, instead of destroying it
> Update modal of first product in product set

- src/updaters/product-set.js
- test/unit/product-set.js
Instead of updating the first product's modal direct, update the entire product. This enables the product's modal to have the correct styles when it opens, since it pulls from the product directly.
> update product instead of modal for product set updates

- src/templates/option.js
Add the missing double quotes around options classes.
Fixes: https://github.com/Shopify/buy-button-js/issues/578
> Add missing double quotes around classes

- package.json
- src/components/cart.js
- src/components/product-set.js
- src/components/product.js
- test/fixtures/product-fixture.js
- test/unit/cart.js
- test/unit/product/product-component.js
- yarn.lock
* Bump js-buy-sdk to v2.7.0, which brings in MoneyV2 fields on the product variant
* Replace use of deprecated fields with `priceV2` and `compareAtPriceV2` 
* Update tests
Tested on Chrome, Safari, Firefox, Opera, Edge, IE10, IE11, Safari iOS
> Bump js-buy-sdk to v2.7.0 and remove use of deprecated fields

- src/components/product-set.js
- test/unit/product-set.js
Only call `showPagination` if the pagination contents option is true
Closes #454 
To test:
* Set the product set pagination contents option to false
* Verify there are no console errors and the pagination button does not render 
* Set the product set pagination contents option to true
* Verify that the pagination button renders, and pagination is functional
> Only show product set pagination if contents option is true

- src/components/cart.js
This PR adds the missing userEvent 'openCheckout' to the onCheckout() function, restoring expected functionality as per the docs: https://shopify.github.io/buy-button-js/customization/#cart-events.
Credit to @hamisor for the fix, this is simply an updated version of #375 with conflicts resolved and style consistent.
> Add missing userEvent 'openCheckout'

- src/components/cart.js
- src/components/product-set.js
- src/components/product.js
- src/utils/track.js
- test/unit/cart.js
- test/unit/product-set.js
- test/unit/product/product-component.js
Currently, when a product set is initialized (i.e. an array of product ids), there is a pagination console error (since product sets do not have connections, it cannot be paginated). This PR fixes this issue by only showing pagination for `collections` and not `product sets`.
Also, the tracking info objects passed to the `tracker` are outdated and some properties are incorrect - this PR will update the tracking info and will also standardize the `id` property to always return the `storefrontId`.
🎩 instructions:
- load a product set buy button and ensure that there are no pagination console error and pagination does not appear in the UI
- load a collection buy button and ensure that pagination is still available and works as expected
> Fix pagination error and update tracking info

- src/components/cart.js
- src/components/product-set.js
- src/components/product.js
- test/unit/cart.js
- test/unit/product-set.js
- test/unit/product/product-component.js
Add 2 new tracking events:
- `Open cart checkout` event: triggers when a user clicks on the checkout button from the cart
- `Open modal` event: triggers when a user clicks on the view product details button
Also, the product set tracking info was updated to contain a new `isProductSet` flag.
> Add new tracking events

- src/styles/embeds/sass/initializers.css
* Set `text-rendering` to auto to prevent safari from crashing when a select is clicked
To 🎩 : 
* For a product with multiple variants, verify that the selects can be used in safari 13
* Check that selects still work in other browsers
> Fix text rendering bug in safari 13

- src/components/cart.js
- src/components/product.js
- src/components/toggle.js
- test/unit/cart.js
- test/unit/product/product-component.js
- test/unit/toggle/toggle-component.js
* Reconfigure cart component to only create a checkout when an item is added to cart
* Add additional checks when accessing data from the cart model, since it won't always be defined
> Defer checkout creation to when variants are added to cart

- docs/customization/index.md
This is just a quick update to one of the docs! One of the links was giving a 404 because the extension was misspelled.
> Fix a broken link

- src/components/product.js
- test/unit/product/product-component.js
When storefrontId is an empty array, we still attempt to make a JS Buy SDK call to Storefront API. We should be more defensive and not make SDK calls in this case.
The API response from one of these calls is:
```
{"errors":[{"message":"Variable id of type ID! was provided invalid value","locations":[{"line":1,"column":804}],"extensions":{"value":null,"problems":[{"path":[],"explanation":"Expected value to not be null"}]}}]}
```
> Prevent API call when storefrontId is an empty array

- src/styles/embeds/sass/components/collection.css
- src/styles/embeds/sass/components/select.css
Due to a `PostCSS` spec difference from `SCSS`, the top margin for collection product tiles were not compiled correctly.
> Fix margin top spacing for collection product tiles

- package.json
- yarn.lock
Update JS Buy SDK to `v2.9.2` - this fixes possibility of Storefront API/JS Buy SDK from returning language content and creating a checkout based on the user's browser's language settings.
> Update JS Buy SDK to v2.9.2

- package.json
- yarn.lock
* Update `shopify-buy` package to latest version ([v2.10.0](https://github.com/Shopify/js-buy-sdk/releases/tag/v2.10.0))
> Bump js-buy-sdk to v2.10.0

- src/components/product.js
- test/unit/product/product-component.js
Currently, when a product's button is disabled (e.g. no stock), it's rendered with `undefined` as class:
```html
<button disabled="" class="shopify-buy__btn undefined " data-element="product.button"></button>
```
This patch fixes this by using the intended default class `shopify-buy__btn-disabled`:
```html
<button disabled="" class="shopify-buy__btn shopify-buy__btn-disabled " data-element="product.button"></button>
```
> Fix CSS class for a product's disabled button

- src/components/cart.js
Currently, when a discount doesn't have a title (e.g. manual discount codes), `UNDEFINED` is displayed in the cart's line item, and nothing is shown next to the label icon in the cart's footer.
This patch fixes this by falling back to displaying the discount code.
> Show a discount's code in the cart if it does not have a title

- src/views/modal.js
Currently, each time a product modal is opened, a new click event listener is added to the same unique overlay. So, when the uses clicks outside of the modal to close it, the event `options.modal.events.closeModal` (if any) is called multiple times, one for each time a modal has been opened. 
This patch fixes this by calling `removeEventListener` for the overlay click event when the modal is closed.
> Prevent modal.events.closeModal from being called multiple times

- src/components/product-set.js
This should fix #672 - conditional check if productSet iframe is false
Added a conditional to ```productConfig``` ```node``` setting in   ```ProductSet``` ```renderProducts``` method 
```javascript
const productConfig = Object.assign({}, this.globalConfig, {
node: this.view.document.querySelector(`.${this.classes.productSet.products}`),
options: merge({}, this.config, {
product: {
iframe: false,
classes: {
wrapper: this.classes.productSet.product,
},
},
}),
});
// fix for #672 - code updated after the 'build fail'
if (this.config.productSet.iframe === false) {
productConfig.node = this.node.querySelector(`.${this.classes.productSet.products}`);
}
```
> Fixed issue #672 - multiple collections rendered in random DOMs regardless of client config when iframe for productSet is FALSE

- src/components/cart.js
- src/utils/focus.js
- src/view.js
- src/views/modal.js
- test/test.js
- test/unit/cart.js
- test/unit/focus.js
- test/unit/modal/modal-view.js
- test/unit/view.js
* Add a common utility to trap focus within a given container
* This function also focuses the first element in the container by default
* Call focus trap function from existing `setFocus` function, which is used by both the cart and modal
* The first element focusing was removed from `setFocus` since that is handled in the focus trap function
* Update modal and cart to remove the focus trap event listeners on close
To 🎩 : 
Cart:
* Open the cart
* Continuously tab forwards through the cart and verify that focus stays in the cart
* Continuously tab backwards through the cart and verify that focus stays in the cart
* Close the cart by hitting enter when focused on the close button
* Focus will stay on the close button (will be fixed in a followup PR)
* Tab backwards and verify that other …
> Add focus trap when cart or modal are open

- src/components/product.js
- src/defaults/components.js
- src/templates/product.js
- test/unit/product/product-component.js
* Add new helper functions in the product component to return the price and compare at price accessibility labels
* Price accessibility label will return `regular price` if there is no compare at price
* Price accessibility label will return `sale price` if there is a compare at price
* Compare at price will return `regular price` if there is a compare at price
* Update template logic to use a helper function to determine if compare at price should be displayed
* It was previously using the legacy `compareAtPrice` field on the variant's model 
* Add new text options to the product config
**To 🎩 :** 
* Create a buy button for a product that has a compare at price, and a product that does not have a compare at price
* Note: VoiceOver works best in safari
Product tile: 
* Navigate a virtual …
> Add price and compare at price accessibility labels

- src/components/cart.js
- src/components/modal.js
- src/components/product.js
- src/components/toggle.js
- src/views/toggle.js
- test/unit/cart.js
- test/unit/modal/modal-component.js
- test/unit/product/product-component.js
- test/unit/toggle/toggle-component.js
- test/unit/toggle/toggle-view.js
* Add a new property to the product component to track whether the product is rendered in the modal or not
* Use the new property to determine whether or not the last active element should be set to the button when the add to cart button is clicked
* If the product is not a modal product, the active element should be set so focus is returned to the button
* If the product is a modal product, the active element should not be set because the modal is closed when the button is clicked, so focus should not be returned to that button in the modal
* Set the active element to the toggle when the cart is opened via the toggle 
* This had to be set in two places since the click and keydown events are handled separately
* Fix a double call to `setFocus` when the cart is opened
* Previously there …
> Return focus to the right element when the cart is closed

- src/views/toggle.js
- test/unit/toggle/toggle-view.js
* Currently, only the enter key can be pressed to trigger the cart toggle
* HTML buttons support both the enter and space key as click triggers when using the keyboard to navigate
* This PR adds support for using the space key to trigger the cart toggle 
* It also calls `preventDefault()` on the event to stop the space key from trigger the page scroll as well 
To 🎩 : 
* Tab to the cart toggle
* Verify that cart opens when pressing the space key and the enter key
* Verify that when the space key is used, the page does not scroll down
Browsers: 
* There is a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1487102) in firefox, which causes the cart to close after it's opened. Calling `preventDefault` in the keydown handler still causes it to emit a subsequent `click` event, which is …
> Toggle cart when space key is pressed

- src/styles/embeds/sass/components/select.css
* Remove `overflow: hidden` from the select wrapper so the focus state is not hidden in firefox 
To 🎩 : 
* Verify that the select elements have a visible focus state in the product tile and modal
* Verify that long variant names don't cause the content to overflow and scroll 
Browsers: 
* Custom appearance of inputs overrides default browser focus indicators. Creating a completely custom focus state may be done as a followup, but should not block the fix for Firefox
> Fix select focus state visibility in firefox

- src/defaults/components.js
- src/templates/cart.js
* Use `aria-hidden="true"` instead of  `aria-role="hidden"` so the `X` is not read by the screen reader 
* Make the accessibility label configurable by exposing it in the cart options
* Update the label from `Close` to `Close cart` for clarity
**To 🎩 :** 
* Navigate a virtual cursor to the cart close button
* Verify that the screen reader does not announce `Times` (this is what it reads out for the `X`)
* Verify that the screen reader announces `Close cart` when the virtual cursor is on the close button
* Update the buy button config, and change the `cart > text > closeAccessibilityLabel` text and verify that it is reflected in the buy button
Browsers
> Update cart close accessibility label

- src/components/cart.js
- src/templates/cart.js
- test/unit/cart/cart.js
* Create a helper in the cart component to create a unique id for the cart note input
* Using a hardcoded id like `CartNote` might end up causing issues if the multiple non-iframe carts exist on the same page 
* The helper uses `Date.now()` to ensure that the id is unique, and it is regenerated each time the cart is rendered
* An alternative that was considered was to add a `createdAt` attribute to the cart, and set it to `Date.now()` in the constructor. However, there is still a chance that two carts could be created at the same time (depending on the JS execution time) 
* Add an `id` attribute to the cart note text area and set it to the unique id
* Change the cart note label from a `<p />` to a `<label />` and set it to the unique id 
* The `for` & `id` method was chosen instead of …
> Connect the cart note label to the textarea

- src/styles/embeds/sass/components/product.css
* Increase opacity to 0.76
* This is the minimum opacity where the default #4a4a4a colour will have a contrast of at least 4.5:1 on a white background
To 🎩 : 
* Create a buy button for a product with a compare at price 
* Verify that the opacity of the compare at price in the product tile is 0.76
* Verify that the opacity of the compare at price in the modal is 0.76
> Increase opacity of compare at price to improve contrast

- src/components/product.js
- src/templates/option.js
- test/unit/product/product-component.js
* Pass in a unique id to the option template, which is made up of the current time and the index of the option
* Set the option select's `id` attribute and the label's `for` attribute to this id
To 🎩 : 
* Create a collection buy button, with multiple products with multiple variants
* Verify in the DOM that none of the selects have the same id
* Navigate a virtual cursor to a product with multiple variants
* Verify that the label is read when announcing the select in VoiceOver
* Verify that the label is announced as clickable when using the virtual cursor, and is announced when tabbing to the select in NVDA
* Create a modal buy button for a product with multiple variants
* Navigate a virtual cursor to the modal
* Verify that the label is read when announcing the select in VoiceOver
* …
> Connect variant label to select

- src/components/cart.js
- src/defaults/components.js
- src/templates/line-item.js
- test/unit/cart/cart.js
* Update the visually hidden text on the decrement and increment button to be clearer
* Abstract out the quantity input aria-label into the config 
To 🎩 : 
* Navigate a virtual cursor through a cart with a line item
* Verify that the quantity decrement button label is `Reduce item quantity by one`
* Verify that the quantity input label is `Quantity` 
* Verify that the quantity increment button label is `Increase item quantity by one`
* Update the three new strings in the buy button config, and verify that they are applied to the buy button
> Update line item quantity accessibility labels

- src/components/cart.js
- src/templates/cart.js
- test/unit/cart/cart.js
* Wrap cart line item list in a `<ul />` 
* Wrap each line item in a `<li />`
* Add a list role to the `<ul/ >` to address a [Safari VoiceOver bug](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style#Accessibility_concerns)
* I didn't opt for the solution posted in MDN since it's more of a hack rather than a permanent solution. This was adding whitespace above the line item product title
**To 🎩** 
* Navigate a virtual cursor to a cart with line items
* Verify that the screen reader announces the line items as a list 
Browsers:
* Sanity check that cart doesn't look visually different
Browsers:
> Use list markup for cart line items

- CHANGELOG.md
Update changelog for `v2.3.0` update - includes updating JS Buy SDK to `v2.19.0`
> Update changelog for v2.3.0

- package.json
- yarn.lock
- WDIO had no config file, seems fine to remove. 
- Upgrading `sass` means we don't need an outdated python version to build some other submodule.
`yarn install` && `yarn build` produce good output.
> Fix build by upgrading/removing deps

- src/iframe.js
- test/unit/iframe.js
- testem-ci.json
- testem.json
Copy of https://github.com/Shopify/buy-button-js/pull/867 to restore firefox tests.
> Fix firefox testing

- .changeset/nine-ties-fly.md
- package.json
- yarn.lock
Updates Buy Button to use JS Buy SDK v3.
This PR trigger a major release for the Buy Button to v3
> Upgrade JS Buy SDK to v3

- .changeset/thirty-hats-cross.md
- package.json
- yarn.lock
Following the steps in https://github.com/Shopify/buy-button-js/blob/main/DEPLOYING.md
> Bump shopify-buy to 3.0.5
