Shopify/buy-button-js

src/components/cart.js
src/components/product-set.js
src/components/product.js
src/ui.js
src/utils/track.js
test/unit/tracker.js
test/unit/ui.js

uses correct event keys and calls `track` on view of products and collections
@richgilbank

fix tracking

---

src/component.js
src/defaults/money-format.js
src/utils/money.js
test/test.js
test/unit/money.js

make sure that empty money strings and bad money strings don't break everything. 
Also made sure money.js passed linting, and copied over the test suite from money.coffee
@tanema @michelleyschen @harisaurus

format money better

---

src/styles/embeds/sass/components/_product.scss

Fixes https://github.com/Shopify/buy-button-js/issues/302
@tanema @tessalt @michelleyschen

fix small sizing issue for options container

---

package.json
script/deploy.js

if this works properly can use across repos 👍 
@michelleyschen @tanema @harisaurus

use uploader package to upload to s3 and npm

---

src/styles/embeds/sass/components/_select.scss

Fixes https://github.com/Shopify/buy-button/issues/2051
@tanema @michelleyschen @tessalt

hide caret for selects in ie

---

src/component.js
src/components/cart.js
src/components/modal.js
src/components/product-set.js
src/components/product.js
src/updater.js
src/updaters/cart.js
src/updaters/modal.js
src/updaters/product-set.js
src/updaters/product.js
test/unit/cart.js
test/unit/product-set.js
test/unit/product.js

extracted `updateConfig` methods out to `Updater` classes, which components delegate to. Considered multiple approaches to this including subclassing and mixins but ultimately let's prefer composition over inheritance why not. 
@tanema @michelleyschen @harisaurus

move updateConfig methods

---

src/component.js

this will support those cases where the DOM is manipulated after the page is loaded, causing the iframe to reload. 
Also fun fact you can right-click on the iframes and select "reload" and now it works. 
@harisaurus @tanema @michelleyschen

support reloading iframes

---

src/components/product.js
src/updaters/modal.js

typo 😧 
adds better error handling as well. 
@michelleyschen @tanema @harisaurus

Fix updateconfig

---

package.json
src/buybutton.js
src/components/cart.js
test/unit/cart.js

pull in smaller image for the cart so we're not scaling down gigantic images. 
@michelleyschen @harisaurus @tanema

use smaller cart image

---

src/components/cart.js
src/components/product.js

prevents weird bad javascript math
@michelleyschen @richgilbank

parse integers from inputs

---

docs/customization/index.md
src/styles/embeds/sass/components/_modal.scss
src/views/modal.js
test/unit/modal.js

* slideOut animation was missing
* the transition is relative to `is-active` class, and therefore the `transitionend` listening should toggle `is-active` instead of `is-block`
* update doc for component that does not have its own life cycle hooks

Modal fixes

---

package.json

update js buy

---

src/components/product.js
src/ui.js

allows cool things like single-page-app things. @tanema @harisaurus @michelleyschen

pass a function to buttonDestination

---

src/components/product.js

The main image wasn't updating in the DOM on variant change or thumbnail click. This PR resolves that issue. Work was done by Tessa, just PR-ing and reviewing.

fix image source

---

src/defaults/components.js
src/templates/cart.js
src/templates/line-item.js
src/templates/modal.js
src/templates/option.js
src/templates/product.js
src/templates/toggle.js

makes it easier for consumers to be able to tell which elements are which if they need to customize. 
@harisaurus @michelleyschen

add data-element to templates

---

docs/_sass/custom/custom.scss
docs/configuration/index.html

Take as many or as little as you like @tessalt 
A lot of these are suggestion.

Docs update review

---

src/components/product.js

Bugfix - ensure selectedVariant has image before checking for variants

fix for image getter handling

---

package.json
yarn.lock

Bumping Js Buy SDK

---

src/styles/embeds/sass/components/product.css

Quick fix for a bug in buybutton.
This code could do with some clean-up which I'll tackle in a separate PR.

ensure modal content is left aligned

---

src/components/cart.js
src/components/checkout.js
src/templates/line-item.js
test/unit/cart.js

fixing how products are added, updated, and removed form the cart, as well as how a checkout is generated.
since there is a perceptible delay when updating items in the cart, my next PR will contain performance improvements (caching + client side calculations), for modifying the cart.

fix cart + checkout

---

.babelrc
package.json
script/build.js
src/buybutton.js
yarn.lock

this pr manually adds polyfills from `core-js` in order to support many of the newer language features that i've been using while working on this library.

IE10 support

---

package.json
yarn.lock

This version has fixes for `fetchNextPage` in it.

Upgrade to beta 4 of js buy

---

package.json
yarn.lock

Hopefully resolves all the pagination issues in the underlying graphql client

Update to shopify buy beta 5

---

docs/index.md
readme.md

Addes a note on the docs site and in the `readme` to point readers to the github issues page for buybutton.js

Add note to point readers to Issues page

---

docs/index.md

- Bump IE version
- Update `buildClient` snippet

update docs to reflect replatforming changes

---

src/styles/embeds/sass/components/collection.css

smal styling fix to add spacing between products for small/mobile breakpoint.

add gutter space between products for small/mobile breakpoint

---

src/templates/product.js

Closes [this issue](https://github.com/Shopify/buy-button/issues/2332).

Use descriptionHtml to show proper formatting

---

src/components/product.js
src/templates/product.js
src/views/product.js
test/unit/product.js

Closes [#2334](https://github.com/Shopify/buy-button/issues/2334)

Remove NO_IMG_URL as a fallback image and render nothing

---

src/templates/cart.js
src/templates/line-item.js

This will fix [#2335](https://github.com/Shopify/buy-button/issues/2335)

Don't escape HTML for money formatting

---

src/components/product.js
test/unit/product.js

Clicking `add to cart` with any quantity was always adding 1 to the cart.

Fix variant quantity that's put in the cart

---

shipit.yml

Reverts Shopify/buy-button-js#460

Revert "Update shipit"

---

shipit.yml

Reverts Shopify/buy-button-js#461

Revert "Revert "Update shipit""

---

package.json
yarn.lock

To address [this issue](https://github.com/Shopify/js-buy-sdk/issues/498#issuecomment-398611027)

Bump js-buy-sdk version

---

src/components/cart.js
test/unit/cart.js

Closes #488 
Currently storefront api returns line items containing variants which have been deleted. This PR adds sanitization to the checkout returned from js-buy-sdk, which will remove any line items that have null variants. These line items must be removed via the js-buy-sdk, rather than just being hidden from the ui, since they're included in the checkout's subtotal. 
To test:
1. Create buy buttons for multiple products with variants, with a button destination of cart
2. After embedding them in a page, add some variants to your cart
3. In admin, delete a variant that's in your cart 
4. Refresh the buy button page
5. Verify that the cart no longer contains the deleted variant, and the subtotal is correct
6. You can also try removing an entire product, and verify that the checkout's …

Remove line items with null variants

---

test/unit/ui.js

- Grouped cart methods together
- Switched from using .then() to async await
- Updated createCart method
- Added tests for toggleCart, closeCart, and openCart

Update ui.js Cart Tests

---

test/unit/ui.js

- Grouped component methods together
- Created tests for component methods
- Removed dependency on destroyComponent in createComponent
- Updated existing tests in component methods

Update ui component tests

---

test/unit/ui.js

- added tests for modal methods
- removed dependency on destroyComponent
- created tests for setActiveEl and restoreFocus

Updated modal methods, setActiveEl, and restoreFocus in ui.js

---

test/unit/ui.js

- created tests for all the getters in ui.js

updated getter tests in ui.js

---

test/unit/ui.js

- Created tests for private methods in ui.js
- Changed a spy into a stub
- Cleared modal and carts after creation due to a bug with cleanup
- Changed UI.prototype to ui in stubs to be consistent through the test

Update Tests for Private Methods in UI.js

---

test/unit/component.js

- Really simple eslint fixes and separated constructor from other tests
- Purpose of this is to make future PRs easier to read

separated constructor and fixed eslint errors in component.js test

---

test/unit/component.js

- extracted instantiation to a beforeEach
- updated existing constructor tests
- created new constructor tests

Updated constructor tests in component

---

test/unit/view.js

- Preliminary reformatting to make future PRs simpler to read
- Separated constructor from rest of prototype methods
- Fixed eslint errors

Format view.js tests

---

test/unit/component.js

Added tests for getters
Added test for private methods
Updated existing tests to meet standards
Added missing tests for existing tests

Update Tests for Prototype Methods in component.js

---

test/unit/view.js

- abstracted instantiation of component and view to a beforeEach() for prototype methods
- updated constructor tests
- updated init tests

Update constructor and init in view.js tests

---

test/unit/view.js

The following methods in view.js have been updated/added:
- render
- delegateEvents
- append
- destroy
- renderChild
- updateNode
- wrapTemplate

Update prototype method tests in view.js part 1

---

test/unit/view.js

The following tests have been created/updated:
- reloadIframe
- addClass
- removeClass
- setFocus
- animateRemoveNode
- removeNode

Update Prototype Method Tests in view.js Part 2

---

test/unit/view.js

Updated tests for getters and private methods in view.js

Update Getters and private methods tests in view.js

---

test/unit/template.js

- Refactored format to be consistent with other tests
- Tested behaviour of Mustache in render() due to being unable to test external libraries
- Renamed variable names and values
- Created test for constructor
- Edited test descriptions

Update template.js tests

---

test/unit/updater.js

- Refactored tests to fit standards of other tests
- Refactored and added tests to updateConfig()

Update updater.js tests

---

test/unit/iframe.js

Created/updated tests for:
- loadFontScript
- setWidth
- addClass
- removeClass
- setName
- updateStyles
- appendStyleTag

Update iframe.js tests part 2

---

test/unit/iframe.js

Added tests for:
- get width
- get document
- get conditionalCSS
- get css
get customStyles due to how complicated it is will be saved for another time. However, get css currently indirectly tests customStyles.

Update iframe.js getters tests

---

test/fixtures/product-fixture.js
test/unit/product.js

Replaced non-existent images with existent ones to fix console errors appearing in test environment.

fixed image console errors in unit test environment

---

test/unit/product/product-component.js

Updated onButtonClick in product.js
- Created tests for when buttonDestination is a function or modal
- Separated existing test for cart buttonDestination into smaller tests
- Added tests for function calls
- A test for when config.cart.popup is false was not made because testing the window location is not possible

Update product component on button click test

---

test/unit/product/product-component.js

Updated tests for:
- onCarouselChange
- openModal
- setDefaultVariant
Created tests for:
- stopPropagation
- openOnlineStore

Update product component prototype methods part 2

---

test/unit/product/product-component.js

- removed non fetch and fetch method groups
- moved sdkFetch into group with all other prototype methods
- refactored sdkFetch to no longer instantiate new product components

component.js sdkFetch Test Refactor

---

test/unit/product/product-component.js

Updated existing tests for the following getters:
- shouldUpdateImage
- currentImage
- viewData
- buttonText
- buttonEnabled
- variantExists
- hasVariants

Update product.js getters tests Part 1

---

test/unit/product/product-component.js

Updated existing tests for:
- requiresCart
- buttonActionAvailable
- isButton
- DOMEvents
- onlineStoreParams
- onlineStoreQueryString
- onlineStoreURL

Update product.js getters tests Part 2

---

test/fixtures/product-fixture.js
test/unit/product/product-component.js

Created tests in product.js for:
- fetchData
- onCarouselItemClick
- nextIndex
- updateQuantity

Update product component prototype methods pt4

---

test/unit/product/product-component.js

Created/Updated tests for:
- image
- formattedPrice
- formattedCompareAtPrice
- carouselImages
- buttonClass

Update product.js getters tests Part 3

---

test/unit/product/product-component.js

Created tests for:
quantityClass
variantInStock
hasQuantity
priceClass
trackingInfo
selectedVariantTrackingInfo

Update Product.js Getters Tests Part 4

---

test/unit/product/product-view.js

Updated every getter and method in product.js within the view folder

Update product.js view tests

---

test/unit/product/product-updater.js

Refactored and created tests in updateConfig for product.

Updated test in product.js in updater

---

test/test.js
test/unit/toggle/toggle-view.js

Created tests for toggle view in new test file, toggle/toggle-view.js

Created Tests for Toggle View

---

test/test.js
test/unit/modal/modal-updater.js

Created tests in new file, modal/modal-updater.js for single function, updateConfig

Created tests for modal updater

---

test/test.js
test/unit/modal/modal-view.js

Created new tests for modal.js in view folder
Tests live in modal/modal-view.js

Created modal view tests

---

docs/index.md

Let's be clearer about which version of the SDK to include.
Closes #388

Update "Including the library" docs

---

CHANGELOG.md
docs/customization/index.md
docs/index.md

* Add a changelog entry for v1
* Update docs with newly exposed configurations options

Update docs for v1.0.0 with discounts

---

src/buybutton.js

Fix how `ShopifyBuy.UI` is set.

Fix UI declaration within Shopify Buy

---

.github/probots.yml

* Enable the CLA bot for the repo

Enable cla probot

---

src/components/product-set.js
test/unit/product-set.js

Fix product set `trackingInfo` to return individual product information.

Fix product set tracking info

---

CODE_OF_CONDUCT.md

Update the link to report abusive, harassing or other types of unacceptable behavior.

Update code of conduct report link

---

CHANGELOG.md

* Add changelog posts for v2.1.2 and v2.1.3

Update changelog for v2.1.3

---

.gitignore
test/unit/cart.js
test/unit/modal/modal-view.js

Add unit tests to cover #692 #686

Add unit tests to cover PRs #686 and #692

---

.github/dependabot.yml
.github/workflows/npm-release.yml
.github/workflows/snapit.yml

Reverts Shopify/buy-button-js#899

Revert "Pin GitHub Actions to commit"

---

.github/dependabot.yml
.github/workflows/npm-release.yml
.github/workflows/snapit.yml
package.json

Reverts Shopify/buy-button-js#908

Revert "Revert "Pin GitHub Actions to commit""

---

.changeset/iframe-accessibility-title.md
CHANGELOG.md
src/defaults/components.js
src/iframe.js
src/view.js
test/unit/iframe.js
test/unit/view.js

Closes https://github.com/Shopify/buy-button/issues/6834
The initial "Add to Cart" control iframe was missing a `title` attribute, which caused accessibility issues for screen reader users. Without a title, screen readers would announce generic text like "frame 0" or the src value, which doesn't describe the purpose of the iframe.
This PR adds meaningful `title` attributes to all iframe elements created by the Shopify Buy Button SDK, improving accessibility for users with screen readers and other assistive technologies.
- Added support for `title` attribute in iframe constructor
- Iframe element now sets the title attribute when provided in config
- Maintains backward compatibility
- Implemented intelligent title determination based on component type
- **Product component**: Uses …

🎯 Add `title` attribute to iframes for accessibility
